### ISSUE TITLE
Unknown at rule: @value > postcss plugins not allowed

### ISSUE THREAD

**Issue by chrisdugne** [indooorsman/esbuild-css-modules-plugin#35]
Hello,

I got error when using `@value` annotation:

```
✘ [ERROR] [plugin esbuild-css-modules-plugin] Unknown at rule: @value
```

example using: 

```css
@value colors: "./colors.css";
@value dark from colors;

.button {
  background-color: dark;
}
```
